name: alistvideos
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  http: ^0.13.3
  intl: ">=0.14.0"
  sqflite:
  flutter_swipe_action_cell: ^2.1.1
  fluttertoast: ^8.0.1-nullsafety.0
  provider: ^5.0.0
  image_picker: ^0.8.2
  image_cropper: ^1.3.1
  #flutter_slidable: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  #fonts:
  #  - 

  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/ic_history.png
    - assets/images/ic_all.png
    - assets/images/ic_today.png
    - assets/videos/
    - assets/videos/intro_1.mp4


